version: '3'
services:
  api:
    container_name: api
    image: api
    build: .
    ports:
      - '3000:3000'
    restart: unless-stopped
networks:
  default:
    external: true
    name: nginx-network